### ISSUE TITLE
E-mail logs?

### ISSUE THREAD

**Issue by ks93** [ks93/xlogger#11]
@Vr93 What do you think?
```python
logger.email('heyy!', to='vr@gmail.com')
```

Would of course need some `max_freqency` parameter

**Comment by Vr93** [comment]
Using email in Python (or any programming language?) you need to configure path to SNMP servers etc. This might be hard to configure for people using the xlogger library.
https://docs.python.org/3/library/email.examples.html

**Comment by ks93** [comment]
yes, lets close this for now and rather reopen it if it makes sense later
